### ISSUE TITLE
Visual glitches with Elementary theme

### ISSUE THREAD

**Issue by giovannicaligaris** [midori-browser/core#146]
I just build the latest master on elementary OS Juno and noticed that it does not look like the default photo on the main page.

Am I missing something?

![screenshot from 2018-10-31 10 36 13](https://user-images.githubusercontent.com/26255347/47782786-f5e18d80-dcf8-11e8-8408-7f42273e69dc.png)

**Comment by kalikiana** [comment]
It wouldn't because those screenshots are from the latest stable.

What you're probably referring to is the glitch of the missing spacing around the buttons in the headerbar. For tabs to be visually merged with the toolbar underneath, there can be no `bottom-padding` or `border-bottom` respectively, which is why they're disabled in Midori's CSS.
Unlike other themes (that I know of) Elementary relies on that `padding`, which causes the buttons to seemingly overlap with the toolbar. It doesn't apply a background to the buttons which causes the white to shine through. And it doesn't add any spacing to the toolbar itself.

**Comment by kalikiana** [comment]
Do you have any experience with GTK+3 style CSS theming?

Midori uses a style sheet with "Application" priority which is at `data/gtk3.css` in the source.

**Comment by kalikiana** [comment]
#197 discusses this in more general manner.
