### ISSUE TITLE
How private is private browsing?

### ISSUE THREAD

**Issue by ohreally** [midori-browser/core#230]
Issue #207 suggests that certain downloaded resources (favicons in this case) are shared between Private Browsing mode and Normal Browsing mode.
Even though I don't know the exact implementation, this makes me feel a bit uncomfortable. Could this compromise my privacy?

Just an example; no idea whether this specific exploit would be possible, now or in the future.

User goes to a certain website, in Normal Browsing mode. Website sends a JPEG favicon, and includes an EXIF tag with the requesting IP or some other identifier. Midori in Normal Browsing mode caches this favicon. The next day, the user returns using Private Browsing mode, maybe even over TOR, or maybe not. Midori re-uses the favicon, because it was cached. Website reads EXIF data (JS, Flash, etc.) and sends it to the server. Server can now link the private session to the normal session.

As said, I don't know whether this specific exploit would be possible. But I would still feel more at ease if Private Browsing mode would not share any downloaded and/or uploadable data with Normal Browsing mode.

**Comment by kalikiana** [comment]
There's an important distinction here. Midori may read data which was stored in Normal Browsing also in Private Browsing, this is true. However that doesn't mean websites or scripts have access to that. In slightly more technical terms, there's a separate 'WebKit.WebContext' which has different data storage settings.
Issue #207 actually happens because of the separation: the code always looks for icons in the storage used by normal mode, which private tab will never write any data to.

That said, making the separation stricter is worth considering. For example icons could exclusively be read from the same mode. There's UX implications to be carefully considered, though. Taking this further: no icons? no history? and step by step the browser becomes so empty that you are not very productive anymore. So, the question is, how much the browser can provide in Private Browsing, without saving anything new to disk.

**Comment by ohreally** [comment]
To be able to constructively have this discussion, the term Private Browsing will need to be defined first. And, more philosophically, the reasoning behind the creation of these 2 distinct usage modes.
I haven't really been able to find these definitions at the Midori website, and to my knowledge, no generally accepted definitions exist. But [Wikipedia](https://en.wikipedia.org/wiki/Private_browsing), lacking a better source, says "_This allows a person to browse the Web without storing local data that could be retrieved at a later date._".

For me, private browsing means browsing without the risk of
- my actions being linked directly to me, unless I explicitly link those actions to myself
- one session being linked to any other session; past, current or future
- someone gaining access to my computer being able to track my online presence and/or actions

Meaning that websites cannot identify me, unless I identify myself, for example by logging into a website. And that all my tracks are covered when I end my session.
To this end, no cookies or history should be saved beyond the end of my browsing session. Which is how Midori currently works, according to the FAQ.

But if you're preventing Midori Private from re-using data from previous private sessions, it would be a bit odd to allow it to re-use data that was saved in a non-private session.
Clearly, the Midori binaries should be shared, as should things like system icons; Midori should not have write permissions to those anyway, so there is very little risk of them being altered by a Normal Browsing session. And explicit downloads should be an exception as well, because the user should be allowed to save downloads anywhere she wants. But I think that implicit downloads, including but not limited to cache and favicons, should never be shared between the 2 browsing modes, because I think that that is the only way to guarantee complete privacy.

Obviously, the development team for Midori is free to use different definitions for Private Browsing mode and Normal Browsing mode, and those definitions would be just as correct (or incorrect) as mine. In any case, it would be a good idea to state these definitions on the website, as well as the reasoning or goals that drive those definitions, so that it is clear for all users what to expect from Private Browsing mode as implemented by Midori (I'm not saying the Midori implementation is wrong; it could just as well be my expectation that is wrong).

Coming back to the current issue, I think that it is clear that I would vote for completely separated local storages for the 2 modes, where the local storage for Private mode should be entirely cleared/wiped at the end of each session. :-)

**Comment by kalikiana** [comment]
You're completely right. We should clearly define this and make it as visible as possible since it's a key design aspect. The FAQ aims to explain, and the introductory page you see when you open a Private Browsing window also gives you some pointers. That said, I agree we can do better.
We could have a section in `README.me` that states design goals and explains private browsing - maybe even tweak the primary feature description, although it should remain concise.

**Comment by ohreally** [comment]
Obviously, the IP address gives away the physical location of the user, more or less. And the IP combined with the user agent string may give an indication of which computer is being used. And combining those with things like the window size, or even browsing behaviour, may lead to the user. So there is no 100% guarantee. And it won't harm to also state that on the website.
But then still, you should do whatever you can ('_you_' as in '_Midori_') to try and approach 100% as much as possible. Because '_All About Privacy_' is listed as 1 one the key features.

**Comment by kalikiana** [comment]
I'll close this issue since it's a discussion rather than a concrete proposal. If we can determine tasks to be worked on we can open new issues for those.
