### ISSUE TITLE
Can't build on Slackware 14.2 (glib-2.46.2)

### ISSUE THREAD

**Issue by igortitarenko** [midori-browser/core#248]
Hello,

I can't build Midori on Slackware 14.2 due to glib-2.48 requirement.
Slackware 14.2 uses glib-2.46.2.

Is there any hope for Slackware 14.2?

**Comment by kalikiana** [comment]
The current requirement is first and foremost `WebKitGTK+ 2.16.6` because we'd be missing crucial APIs going to lower major versions. Although I'm not actually sure if `GLib 2.16.2` would or wouldn't work... can I ask you to try your hands on lowering the version in `CMakeLists.txt` on your system and giving it a go? Then we can look at what we might be missing, and if that's feasible.

**Comment by igortitarenko** [comment]
Ok. It works with glib2-2.46.2 on Slackware64 14.2 after I lowered the version in CMakeLists.txt.

Though, had to rebuild system GCR package without "--disable-vala", but that's not your problem.
