### ISSUE TITLE
Confirm button when leaving a page with unsaved changes does nothing

### ISSUE THREAD

**Issue by tux93** [midori-browser/core#276]
The confirm button of the pop-up when leaving a page with unsaved changes does not work, the only way to leave such a page is either quitting Midori or reverting all changes manually.

System is openSUSE Tumbleweed with Midori 7.0

![midori_confirm](https://user-images.githubusercontent.com/1749593/53431627-31633e80-39f1-11e9-9fd8-4fd32a67a67c.gif)

**Comment by kalikiana** [comment]
Hey @tux93 
Thanks a lot for the report. The screencast demonstrating the bug is much appreciated and was quite helpful in highlighting what the problem was.
I made a PR changing the way prompts that require user input are handled from a popover to a dialog (in short: the API we're using doesn't really give us many options).
And this should get in just about in time for the release!
