### ISSUE TITLE
midori snap app (v7-34-g0c5820f) - not able to display chinese correctly

### ISSUE THREAD

**Issue by timeislove** [midori-browser/core#313]
i am running snapd (2.38+) on xubuntu 18.04.2. note the bottom below the config files.

pls check if it was because the snap could not access system font out of the confinement. i checked the midori snap connections, it looks missing the plug desktop in which the latest :desktop should allow access to host system fonts.

~/snap/midori/current/.config/midori$ cat config 

[settings]
default-encoding=UTF-8
last-window-width=1024
last-window-height=551
location-entry-search=http://www.google.com/search?q=%s
auto-load-images=false
load-on-startup=MIDORI_STARTUP_HOMEPAGE
proxy-type=MIDORI_PROXY_NONE

[extensions]
libadblock.so=true

**Comment by kngharv** [comment]
I have multiple laptops running various distribution of ubuntu/lubuntu.
ONE of three laptop display Chinese correctly.  

Since all three laptop's midori config file are empty, I am not sure why only one of them display Chinese correctly.

All three laptops actually uses English as default locale (en_CA.utf-8 as example)

I suspect it's more to do with fonts.  But I can't find any documents on how to do a font substitution on the config file.

any pointer will be much appreciated.

**Comment by kalikiana** [comment]
I would recommend to read up on FontConfig, the ArchLinux wiki is an amazing resource in this topic (and many others) even if you're using Ubuntu: https://wiki.archlinux.org/index.php/Font_configuration
