### ISSUE TITLE
Reframe the future Midore

### ISSUE THREAD

**Issue by Poncho09** [midori-browser/core#97]
Possibly this is the characteristic that could most impact the whole community but as the title says it is to refocus the future, the proposal although it is very ambitious is viable and can be executed,

The proposal is to migrate the project to Qt, although I know that it is a somewhat complex task at the technical level, it is viable without ever thinking about changing WebKit.

**Pros**
1. We gain more customization.
1. Midori could reach mobile devices.
1. Creation of new UI and UX with much more easy.
1. Possibility of greater contribution by the community.
1. Integration with new technologies for user interfaces.
1. Separation of the programming layer and the interface layer.
1. Complete restructuring.

**Contra**
1. Greater effort when using webkit.
1. Greater slowness at the time of development and adaptation to new languages.
1. Delay with the roadmap.
1. Others.

**Comment by kalikiana** [comment]
To my mind moving away from GTK+ isn't going to happen. Why? Because integration with the underlying system has been a core goal since the inception of Midori and Qt can't provide that, especially with modern features like CSD. On eg. Android the use of Qt would be much more beneficial, however the size of the app would be significantly larger and the native webkit support is too limited to implement a web browser.

So I'm going to propose an alternative plan. We can work towards different, native frontends which share code. The key to this may be found in the form of Kotlin which supports the JVM and native code.

**Comment by Poncho09** [comment]
Thank you for listening and reading my opinions and my proposals, and thank you for taking them into account @kalikiana, since I am very motivated by this project, and I really want to be part of this alternative.
